//
//  LoginRouter.swift
//  CleanTest
//
//  Created by Ahmed on 24/07/2023.
//  Copyright (c) 2023 Ahmed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
  func routeToHome(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Routing
  
  func routeToHome(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! HomeViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToHome(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "HomeViewController") as! HomeViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToHome(source: dataStore!, destination: &destinationDS)
      navigateToHome(source: viewController!, destination: destinationVC)
    }
  }

   //MARK: Navigation
  
  func navigateToHome(source: LoginViewController, destination: HomeViewController)
  {
    source.show(destination, sender: nil)
  }
  
   //MARK: Passing data
  
  func passDataToHome(source: LoginDataStore, destination: inout HomeDataStore)
  {
    destination.userName = source.userName
  }
}
