//
//  LoginPresenter.swift
//  CleanTest
//
//  Created by Ahmed on 24/07/2023.
//  Copyright (c) 2023 Ahmed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentSignIn(response: Login.SignIn.Response)
    func routeToHome(response : Login.RoutToHome.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
    
    func presentSignIn(response: Login.SignIn.Response) {
        
        let viewModel = Login.SignIn.ViewModel(user: response.user, success: response.success, message: response.message)
        viewController?.displaySignIn(viewModel: viewModel)
    }
    func routeToHome(response: Login.RoutToHome.Response) {
        let viewModel = Login.RoutToHome.ViewModel()
        viewController?.goToHome(viewModel: viewModel)
    }
}
