//
//  LoginModels.swift
//  CleanTest
//
//  Created by Ahmed on 24/07/2023.
//  Copyright (c) 2023 Ahmed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
    
    enum SignIn
    {
        struct Request
        {
            var email : String
            var password : String
        }
        struct Response
        {
            var user : UserProfile?
            var success : Bool?
            var message : String?
        }
        struct ViewModel
        {
            var user : UserProfile?
            var success : Bool?
            var message : String?
        }
    }
    enum RoutToHome {
        
        struct Request {
            var userName:String
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
}
