//
//  HomePresenter.swift
//  CleanTest
//
//  Created by Ahmed on 25/07/2023.
//  Copyright (c) 2023 Ahmed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
  func presentUserName(response: Home.ShowUserName.Response)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
  
  func presentUserName(response: Home.ShowUserName.Response)
  {
    let textToDisplay = "Hello Logged in User Name is \(response.userName)"
    let viewModel = Home.ShowUserName.ViewModel(textToDisplay: textToDisplay)
    viewController?.showUserName(viewModel: viewModel)
  }
}
